[mypy]
strict = true
explicit_package_bases = true
mypy_path = src

[mypy-adafruit_pn532.*]
ignore_missing_imports = true

[mypy-qtawesome]
ignore_missing_imports = true

[mypy-pyqttoast.*]
ignore_missing_imports = true
