# Part of this file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import *


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/main_page_assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


class MainPage(Frame):
    def __init__(self, parent, controller):
        super().__init__(parent)
        self.photoList = []
        self.loadWidgets(controller)

    def loadWidgets(self, controller):
        from QRCodes import QRCodes
        from CheckInNoId import CheckInNoId

        canvas = Canvas(
            self,
            bg="#153246",
            height=1080,
            width=1920,
            bd=0,
            highlightthickness=0,
            relief="ridge",
        )

        canvas.place(x=0, y=0)
        image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))

        self.photoList.append(image_image_1)

        image_1 = canvas.create_image(960.0, 540.0, image=image_image_1)

        image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))

        self.photoList.append(image_image_2)

        image_2 = canvas.create_image(959.0, 539.0, image=image_image_2)

        canvas.create_text(
            504.0,
            903.0,
            anchor="nw",
            text="Please tap ID on the black box to start",
            fill="#F5F0E6",
            font=("Inter", 32 * -1),
        )

        canvas.create_text(
            100.5,
            255.0,
            anchor="nw",
            text="SCRIPPS SANDBOX",
            fill="#F5F0E6",
            font=("Refrigerator Deluxe", 113 * -1, "bold"),
        )

        canvas.create_text(

            115.5,
            637.5,
            anchor="nw",
            text="MAKERSPACE",
            fill="#F5F0E6",


            font=("Refrigerator Deluxe", 73 * -1, "bold"),
        )

        image_image_3 = PhotoImage(file=relative_to_assets("image_3.png"))

        self.photoList.append(image_image_3)

        image_3 = canvas.create_image(132.0, 135.0, image=image_image_3)

        button_image_1 = PhotoImage(file=relative_to_assets("image_4.png"))

        self.photoList.append(button_image_1)

        button_1 = Button(
            self,
            image=button_image_1,
            bg="#153246",
            command=lambda: controller.show_frame(QRCodes),
            relief="flat",
            highlightthickness=0,
            bd=0,
        )

        button_1.place(x=79.5, y=82.5)

        button_2 = Button(
            self,
            image=image_image_3,
            text="No\nID",
            compound="center",
            bg="#153246",
            fg="white",
            command=lambda: controller.show_frame(CheckInNoId),
            relief="flat",
            highlightthickness=0,
            bd=0,
            font=("Inter", 36 * -1),
        )

        button_2.place(x=1695.0, y=60.0)
